Integrated client and server
Aditya7298/chatapplication pull request #2
Opened 2021-08-02 11:58 UTC by Aditya7298

* Fixed problems in the previous PR.
* Integrated Client and Server.

2021-08-02 13:12 UTC, Aditya7298 commented
* login screen - <img width="1742" alt="Screenshot 2021-08-02 at 6 40 18 PM" src="https://user-images.githubusercontent.com/46050285/127867299-97c44b4e-6553-4ce0-b2d7-7095042aadc6.png">
* messages in a chatroom - <img width="1742" alt="Screenshot 2021-08-02 at 6 40 38 PM" src="https://user-images.githubusercontent.com/46050285/127867357-8a924b51-aeac-4287-80dc-c7d083f5a11e.png">

2021-08-03 06:06 UTC, hetpatel33 requested changes

2021-08-03 06:06 UTC, hetpatel33 commented on src/components/App.tsx
> +  return <ChatApp />;
Why do we even need this extra component layer if it is doing nothing

2021-08-03 06:06 UTC, hetpatel33 commented on src/components/chatApp/ChatApp.tsx
> +      {userId === "" ? (
Why do we want to compare userId with empty string? Why can't we have check for defined value

2021-08-03 06:06 UTC, hetpatel33 commented on src/components/chatArea/ChatArea.tsx
> +    url: `http://localhost:8080/chatrooms/${chatRoomId}`,
Can we move this http://localhost:8080 to some env file? instead of hardcoding

2021-08-03 06:06 UTC, hetpatel33 commented on src/components/hooks/useQuery.ts
> +  const skip = params.skip || false;
`const { url, method, payload, skip = false } = params;`

2021-08-03 06:06 UTC, hetpatel33 commented on src/components/login/Login.tsx
> +    if (data) {
Why not have check for data.userId instead of whole data? 
Also, why not add only data.userId in dependency array

2021-08-03 06:06 UTC, hetpatel33 commented on src/components/main/Main.tsx
> +    null
Why null and not undefined

2021-08-03 06:06 UTC, hetpatel33 commented on src/components/message/Message.tsx
> +    url: `http://localhost:8080/messages/${messageId}`,
Why do we need to pass this base url (http://localhost:8080) each time when we use useQuery, can we not have it directly inside the useQuery?

2021-08-03 06:06 UTC, hetpatel33 commented on src/components/sidebar/Sidebar.tsx
>          <span onClick={() => setShowPersonalChats(!showPersonalChats)}>
You should use prev value instead of using the state directly

2021-08-03 09:54 UTC, Aditya7298 commented on src/components/main/Main.tsx
> +    null
for a variable whose value is not set right now, should I use null or undefined ??

2021-08-03 12:01 UTC, merged